### ISSUE TITLE
PS5CameraTweaker is virus?

### ISSUE THREAD

**Issue by brcd1** [PavlikBender/PS5CameraTweaker#1]
My Windows Defender says the file is malicious. What should I do?
![image](https://github.com/user-attachments/assets/f43aced4-bb90-4def-aa16-aaa6c3720976)

**Comment by PavlikBender** [comment]
Странно, я не писал ничего такого, что бы лезло куда то кроме firmware.bin. Собственно поэтому тут исходники лежат, можешь сам убедиться, что там нет ничего вирусного. Не поленился запустил проверку через Windows Defender:
![Снимок экрана 2024-08-19 163257](https://github.com/user-attachments/assets/5f162fcb-3f10-45c5-ab2a-10635b24d5d6)
Прогнал через Dr.WEB:
![image](https://github.com/user-attachments/assets/71b867a3-cf7c-4ebc-9846-2af33ad3153c)

**Comment by brcd1** [comment]
> Странно, я не писал ничего такого, что бы лезло куда то кроме firmware.bin. Собственно поэтому тут исходники лежат, можешь сам убедиться, что там нет ничего вирусного. Не поленился запустил проверку через Windows Defender: ![Снимок экрана 2024-08-19 163257](https://private-user-images.githubusercontent.com/88476922/359119075-5f162fcb-3f10-45c5-ab2a-10635b24d5d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxMDIyMDMsIm5iZiI6MTcyNDEwMTkwMywicGF0aCI6Ii84ODQ3NjkyMi8zNTkxMTkwNzUtNWYxNjJmY2ItM2YxMC00NWM1LWFiMmEtMTA2MzViMjRkNWQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDIxMTE0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2M2ZlNzZiMmZlNzkzMDdhYWE3NDc5NTNiYWJjMmY1Y2U1YTZhNTg1NmQ0MDZjMGI1NGExNzJlYWQwMDVhNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GvH5HFcdLe0xjRZg2kz8r-1-hjSlr-RFe2eKrz_7fc0) Прогнал через Dr.WEB: ![image](https://private-user-images.githubusercontent.com/88476922/359119477-71b867a3-cf7c-4ebc-9846-2af33ad3153c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxMDIyMDMsIm5iZiI6MTcyNDEwMTkwMywicGF0aCI6Ii84ODQ3NjkyMi8zNTkxMTk0NzctNzFiODY3YTMtY2Y3Yy00ZWJjLTk4NDYtMmFmMzNhZDMxNTNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDIxMTE0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1MWE2Zjk5YjdhODNlMzFmYzE2ZmQ4OWMxOGIzYzg0NmVlZmE2NjhmZTc3YWM2YjM1ZmQ5OWIwNjRkYzRiZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Zbqg7uYu5ZtYIdOV1bRnWhznDkwXD7I7jF5v70ynrZ4)

Интересно получилось, еще раз скачал (спустя 8 часов) и защитник даже не пискнул. Полтергейст какой-то XDDD

**Comment by PavlikBender** [comment]
Тогда закрываю Issue
